import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/module/Header";
import Footer from "@/components/module/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="relative z-[1] flex min-h-screen flex-col antialiased">
        <Header />
        <main className="flex-grow overflow-x-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
